import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

// Runs only in the caller's disposable test profile; no real saves or Boxes.
export async function checkBoxTransfers({ page, evaluate, delay, tempRoot }) {
  const result = await evaluate(page, `(async () => {
    const el = id => document.getElementById(id);
    const check = (value, message) => { if (!value) throw new Error(message); };
    const wait = async predicate => { for (let i=0;i<150;i++) { if (predicate()) return; await new Promise(r=>setTimeout(r,100)); } throw new Error('Box transfer timed out'); };
    for (const dialog of document.querySelectorAll('dialog[open]')) dialog.close();
    el('boxes-tab').click();
    check(el('export-boxes').textContent === 'Export', 'Export label');
    check(![...document.querySelectorAll('#boxes-list button')].some(button=>/Showdown|Export|Import/.test(button.textContent)), 'No per-card import/export actions');
    el('open-box-import').click();
    check(el('box-import-dialog').open, 'Import chooser');
    check(el('save-import').closest('dialog') === el('box-import-dialog'), 'Save option moved');
    check(el('import-boxes').closest('dialog') === el('box-import-dialog'), 'PLC option moved');
    el('showdown-open').click();
    check(!el('box-import-dialog').open && el('showdown-dialog').open && !el('showdown-text').readOnly, 'Showdown import mode');
    const previousCount = document.querySelectorAll('.box-card').length;
    el('showdown-destination').value = 'new';
    el('showdown-text').value = 'TransferTest (Clefairy)\\nLevel: 26\\n- Pound';
    el('import-showdown').click();
    await wait(()=>!el('showdown-dialog').open && document.querySelectorAll('.box-card').length===previousCount+1);
    el('export-boxes').click();
    check(el('box-export-dialog').open, 'Export chooser');
    const options = [...el('box-export-selection').querySelectorAll('input')];
    check(options.length === previousCount+1 && options.every(input=>input.checked), 'All current-game Boxes initially selected');
    el('clear-box-export').click();
    check(el('confirm-box-export').disabled, 'Empty selection disabled');
    el('select-all-box-export').click();
    check(options.every(input=>input.checked), 'Select All');
    el('clear-box-export').click();
    const selected = options.at(-1);
    selected.checked = true;
    selected.dispatchEvent(new Event('change', {bubbles:true}));
    check(!el('confirm-box-export').disabled, 'One Box enabled');
    el('box-export-format').value = 'showdown';
    el('box-export-format').dispatchEvent(new Event('change'));
    el('confirm-box-export').click();
    check(!el('box-export-dialog').open && el('showdown-dialog').open, 'Showdown export transition');
    check(el('showdown-text').readOnly && el('import-showdown').hidden && !el('copy-showdown').hidden, 'Export has copy, not import controls');
    check(el('showdown-destination').closest('.context-grid').hidden, 'Export has no destination');
    check(el('showdown-text').value.includes('TransferTest') && !el('showdown-text').value.includes('\\n\\n'), 'Only one selected Box exported to Showdown');
    el('showdown-dialog').close();
    el('export-boxes').click();
    el('clear-box-export').click();
    const input = [...el('box-export-selection').querySelectorAll('input')].find(input=>input.value===selected.value);
    input.checked = true; input.dispatchEvent(new Event('change'));
    el('box-export-format').value = 'plc'; el('box-export-format').dispatchEvent(new Event('change'));
    const originalClick = HTMLAnchorElement.prototype.click;
    let captured;
    HTMLAnchorElement.prototype.click = function() { captured = fetch(this.href).then(response=>response.text()); };
    try { el('confirm-box-export').click(); } finally { HTMLAnchorElement.prototype.click = originalClick; }
    check(captured, 'PLC download generated');
    const json = await captured;
    const library = JSON.parse(json);
    check(Object.keys(library.games).length===1, 'Only current game exported');
    const game = Object.values(library.games)[0];
    check(game.boxOrder.length===1 && game.boxOrder[0]===selected.value, 'Only selected Box in JSON');
    const box = game.boxes[selected.value];
    check(box.pokemonOrder.length===1 && box.partyOrder.length===1, 'Party and Pokemon retained');
    const upload = text => { const transfer = new DataTransfer(); transfer.items.add(new File([text], 'selected-box.json', {type:'application/json'})); el('import-boxes').files=transfer.files; el('import-boxes').dispatchEvent(new Event('change',{bubbles:true})); };
    el('open-box-import').click();
    upload('{bad json');
    await wait(()=>el('box-import-status').textContent.length>0);
    check(el('box-import-dialog').open, 'Bad file leaves dialog open');
    upload(json);
    await wait(()=>!el('box-import-dialog').open && document.querySelectorAll('.box-card').length===previousCount+2);
    el('open-box-import').click(); el('showdown-open').click();
    check(!el('showdown-text').readOnly && !el('import-showdown').hidden && !el('showdown-destination').closest('.context-grid').hidden, 'Import restored after export');
    el('showdown-dialog').close();
    return {selectedBoxJson:true, selectedBoxShowdown:true, roundTrip:true, invalidFile:true, oldActionsRemoved:true};
  })()`, true);
  assert.equal(result.roundTrip, true);
  for (const width of [1280,390]) {
    await page.send('Emulation.setDeviceMetricsOverride', {width,height:900,deviceScaleFactor:1,mobile:false});
    await evaluate(page, `document.getElementById('export-boxes').focus(); document.getElementById('export-boxes').click()`);
    await delay(100);
    const dimensions = await evaluate(page, `(()=>{const d=document.getElementById('box-export-dialog');const r=d.getBoundingClientRect();return {left:r.left,right:r.right,width:innerWidth,overflow:d.scrollWidth>d.clientWidth+1};})()`);
    assert.ok(dimensions.left >= 0 && dimensions.right <= dimensions.width && !dimensions.overflow, 'Export dialog fits viewport '+width);
    const shot = await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
    await fs.writeFile(path.join(tempRoot,'box-export-'+width+'.png'),Buffer.from(shot.data,'base64'));
    await page.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
    await page.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
    assert.equal(await evaluate(page,`document.getElementById('box-export-dialog').open`),false,'Escape closes export');
    assert.equal(await evaluate(page,`document.activeElement.id`),'export-boxes','Focus returns to Export');
    await evaluate(page, `document.getElementById('open-box-import').focus(); document.getElementById('open-box-import').click()`);
    const importFits = await evaluate(page, `(()=>{const d=document.getElementById('box-import-dialog');const r=d.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth && d.scrollWidth<=d.clientWidth+1;})()`);
    assert.ok(importFits, 'Import dialog fits viewport '+width);
    const importShot = await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
    await fs.writeFile(path.join(tempRoot,'box-import-'+width+'.png'),Buffer.from(importShot.data,'base64'));
    await evaluate(page, `document.getElementById('box-import-dialog').close()`);
  }
  console.log(JSON.stringify({status:'box-transfer-browser-valid',...result,widths:[1280,390]}));
}
