import assert from 'node:assert/strict';
import path from 'node:path';

// Runs only inside the existing disposable headless-browser smoke profile.
export async function runDraftsFreeCalcSmoke({ page, evaluate, capture, screenshotRoot }) {
  const result = await evaluate(page, `(async () => {
    const wait = async (predicate, label) => { const deadline = Date.now()+20000; while(!predicate()){if(Date.now()>deadline)throw new Error(label+': '+document.getElementById('app-status').textContent);await new Promise(r=>setTimeout(r,40));} };
    const change = (node,value) => {node.value=value;node.dispatchEvent(new Event('change',{bubbles:true}));};
    const click = id => document.getElementById(id).click();
    const discard = setInterval(()=>{if(document.getElementById('destructive-dialog').open)click('destructive-discard');},40);
    change(document.getElementById('game-select'),'volt-white-2r');
    await wait(()=>document.getElementById('trainer-select').querySelector('option[value="vw2r-trainer-0050"]'),'VW2R');
    document.getElementById('plan-context-dialog').close(); click('boxes-tab'); click('showdown-open');
    document.getElementById('showdown-text').value='Clefairy\\nAbility: Magic Guard\\nLevel: 25\\nSerious Nature\\n- Pound\\n- Moonlight\\n\\nSwellow\\nAbility: Guts\\nLevel: 25\\nSerious Nature\\n- Wing Attack\\n- Quick Attack';
    click('import-showdown'); await wait(()=>!document.getElementById('showdown-dialog').open,'import');
    const boxCard=[...document.querySelectorAll('.box-card')].at(-1);
    const grid=boxCard.querySelector('.party-card-grid');
    if(!grid || [...boxCard.querySelectorAll('button')].some(b=>b.textContent==='Edit Party'))throw new Error('Party row did not use editable cards');
    const before=[...grid.children].map(c=>c.dataset.pokemonId);
    if(grid.querySelector('.party-drag-handle'))throw new Error('Visible drag handle should not be present');
    if(getComputedStyle(grid.children[0]).cursor!=='grab')throw new Error('Card surface does not show the drag cursor');
    if(getComputedStyle(grid.children[0].querySelector('select')).cursor!=='pointer')throw new Error('Card selectable does not retain its interactive cursor');
    grid.children[0].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
    if(grid.children[0].dataset.pokemonId!==before[1])throw new Error('Keyboard reorder failed');
    grid.children[1].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));
    if(grid.children[0].dataset.pokemonId!==before[0])throw new Error('Keyboard reorder restore failed');
    click('plc-tab');click('new-plan');await wait(()=>document.getElementById('plan-context-dialog').open,'context');
    const trainer=document.getElementById('trainer-select');
    change(trainer,'vw2r-trainer-0226');
    const format=document.getElementById('battle-format-choice');
    if(format.hidden || format.options.length!==2 || format.selectedIndex!==0)throw new Error('Optional pair must default to Singles');
    const singles=document.querySelectorAll('#enemy-team-summary .context-pokemon').length;
    change(format,format.options[1].value);
    if(document.querySelectorAll('#enemy-team-summary .context-pokemon').length<=singles)throw new Error('Double choice did not include both teams');
    change(trainer,'vw2r-lenora-hawes-double');
    if(!format.hidden || document.querySelectorAll('#enemy-team-summary .context-pokemon').length!==4)throw new Error('Mandatory paired selection is incorrect');
    const box=document.getElementById('context-box-select'); change(box,[...box.options].at(-1).value);
    const party=document.getElementById('context-party-select');change(party,party.options[1].value);click('save-party-selection');
    const summary=document.getElementById('party-selection-summary');
    const firstId=summary.children[0].dataset.pokemonId;
    change(summary.querySelector('.context-pre-status'),'tox');change(summary.querySelector('.context-pre-item'),'leftovers');
    summary.children[0].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
    if(summary.children[1].dataset.pokemonId!==firstId)throw new Error('Setup reorder failed');
    click('begin-plan');await wait(()=>!document.getElementById('plan-context-dialog').open && document.querySelectorAll('#player-action-panel .combatant-card').length===2,'partner plan');
    clearInterval(discard);
    const capture=()=>globalThis.__PLC_TESTING_STATE__.capture();
    const original=capture();
    const library=await (new (await import('./src/boxes/library.js')).IndexedDbBoxLibraryStore()).load();
    const source=Object.values(original.plan.combatants).find(mon=>mon.source.uniqueKey===firstId).source;
    const storedBox=Object.values(library.games).find(game=>game.boxes[source.boxId]).boxes[source.boxId];
    if(storedBox.pokemon[firstId].majorStatus!=='tox'||storedBox.pokemon[firstId].itemId!=='leftovers')throw new Error('Setup edits did not persist to Box');
    document.querySelector('#player-action-panel .move-button:not(:disabled)').click();
    click('save-plan');await wait(()=>/saved to Drafts/.test(document.getElementById('app-status').textContent),'save draft');
    const baseline=capture();
    click('free-calc');await wait(()=>document.querySelector('.free-calc-editor'),'Free Calc');
    if(!document.querySelector('.ai-forecast-panel').hidden)throw new Error('Free Calc AI is visible');
    change(document.querySelector('[aria-label="Free Calc player slot 1 HP"]'),'11');
    await wait(()=>capture().plan.stateNodes[capture().app.cursorStateNodeId].combatantStates[original.plan.stateNodes[original.plan.initialStateNodeId].active.playerCombatantKeys[0]].hp.max===11,'HP override');
    click('free-calc-close');
    if(JSON.stringify(capture().plan)!==JSON.stringify(baseline.plan))throw new Error('Close mutated original plan');
    click('free-calc');change(document.querySelector('[aria-label="Free Calc player slot 1 HP"]'),'12');click('free-calc-add');
    await wait(()=>!document.getElementById('commit-turn').hidden,'Add');
    if(Object.keys(capture().plan.manualTransitions||{}).length!==1)throw new Error('Add did not make a branch');
    click('free-calc');change(document.querySelector('[aria-label="Free Calc player slot 1 HP"]'),'13');
    globalThis.prompt=()=> 'Feature Free Calc';click('free-calc-save');
    await wait(()=>/new Turn 1 draft/.test(document.getElementById('app-status').textContent),'Save as Draft');
    click('drafts-tab');await wait(()=>document.querySelectorAll('.saved-line').length===2,'Draft cards');
    const free=[...document.querySelectorAll('.saved-line')].find(card=>card.querySelector('h2').textContent==='Feature Free Calc');
    if(!free || free.querySelectorAll('.saved-line-node').length!==1)throw new Error('New draft is not one Turn 1');
    return {drag:true,keyboard:true,persistedItemStatus:true,optionalFormat:true,close:true,add:true,saveAsDraft:true,baselineDraftName:baseline.plan.name};
  })()`, true);
  await capture(page,path.join(screenshotRoot,'plc-drafts-feature.png'));
  const eventStart = page.events.length;
  await page.send('Page.reload');
  const loadDeadline = Date.now() + 15000;
  while (!page.events.slice(eventStart).some(event => event.method === 'Page.loadEventFired')) {
    if (Date.now() > loadDeadline) throw new Error('Feature reload did not finish');
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  const reopened = await evaluate(page, `(async () => {
    const wait=async(predicate,label)=>{const until=Date.now()+20000;while(!predicate()){if(Date.now()>until)throw new Error(label);await new Promise(r=>setTimeout(r,40));}};
    await wait(()=>document.getElementById('game-select')&&/Select a game to load/.test(document.getElementById('app-status').textContent),'reload shell');
    const game=document.getElementById('game-select');game.value='volt-white-2r';game.dispatchEvent(new Event('change',{bubbles:true}));
    await wait(()=>!document.getElementById('workspace').hidden,'reload active plan');
    document.getElementById('drafts-tab').click();await wait(()=>document.querySelectorAll('.saved-line').length===2,'persistent drafts');
    const original=[...document.querySelectorAll('.saved-line')].find(card=>card.querySelector('h2').textContent!== 'Feature Free Calc');
    original.querySelector('button').click();await wait(()=>document.getElementById('destructive-dialog').open,'Replace dialog');
    if(document.querySelector('#destructive-dialog h2').textContent!=='Replace Active Line?')throw new Error('Replace title');
    document.getElementById('destructive-discard').click();
    await wait(()=>!document.getElementById('plc-panel').hidden,'opened draft');
    const snapshot=globalThis.__PLC_TESTING_STATE__.capture();
    if(!snapshot.transientTurn.actionDraft.player[0]?.moveId || snapshot.transientTurn.actionDraft.enemy[0]?.moveId)throw new Error('Incomplete actions did not restore');
    document.getElementById('free-calc').click();await wait(()=>document.querySelector('.free-calc-editor'),'Free Calc reopened');
    return true;
  })()`,true);
  assert.equal(reopened,true);
  await page.send('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});
  await evaluate(page,`document.querySelector('.free-calc-editor').scrollIntoView({block:'start'})`);
  await capture(page,path.join(screenshotRoot,'plc-free-calc-desktop.png'));
  await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await evaluate(page,`document.querySelector('.free-calc-editor').scrollIntoView({block:'start'})`);
  await capture(page,path.join(screenshotRoot,'plc-free-calc-mobile.png'));
  await evaluate(page,`(async()=>{document.getElementById('free-calc-close').click();document.getElementById('drafts-tab').click();await new Promise(r=>setTimeout(r,150));globalThis.confirm=()=>true;for(const card of document.querySelectorAll('.saved-line'))[...card.querySelectorAll('button')].find(b=>b.textContent==='Delete').click();await new Promise(r=>setTimeout(r,300));if(document.querySelector('.saved-line'))throw new Error('Delete did not clear drafts');})()`,true);
  return result;
}
