import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

export async function checkTrainerSelector({ page, evaluate, delay, tempRoot, staged = false }) {
  await evaluate(page, `(async () => {
    const wait = async (fn,label) => { for(let i=0;i<500;i++){if(fn())return;await new Promise(r=>setTimeout(r,50));}throw new Error(label); };
    window.waitForSelectorTest = wait;
    await wait(() => document.querySelector('.game-picker-option[data-game-id="platinum-kaizo"]:not(:disabled)'), 'PK game picker');
    document.querySelector('.game-picker-option[data-game-id="platinum-kaizo"]').click();
    await wait(() => document.getElementById('starter-dialog').open, 'PK starter');
    document.querySelector('[data-starter-id="chimchar"]').click();
    document.getElementById('new-plan').click();
    await wait(() => document.getElementById('trainer-selector-dialog').open,'trainer selector');
    if(!document.querySelector('.trainer-continue').disabled) throw new Error('Continue requires a selection');
    const tab=[...document.querySelectorAll('.trainer-split-tabs button')].find(tab=>tab.getAttribute('aria-label')?.includes('Maylene'));
    tab.click();
    const pair=document.querySelector('[data-trainer-id="platinum-kaizo-veilstone-tag-battle"]');
    if(!pair || pair.querySelectorAll('.trainer-block').length!==2) throw new Error('Combined multi encounter');
    const owners=[...pair.querySelectorAll('.trainer-block')].map(row=>({id:row.dataset.ownerTrainerId,cards:row.querySelectorAll('.context-pokemon').length,slot:row.querySelector('.combatant-slot-heading').textContent}));
    if(JSON.stringify(owners.map(owner=>[owner.cards,owner.slot]))!==JSON.stringify([[6,'Slot 3'],[5,'Slot 4']])) throw new Error('Multi ownership labels');
    if(pair.nextElementSibling.dataset.trainerId!=='platinum-kaizo-trainer-0309' || pair.nextElementSibling.nextElementSibling.dataset.trainerId!=='platinum-kaizo-trainer-0310') throw new Error('Canonical trainer navigation');
    if(pair.textContent.includes('#') || pair.textContent.includes('Selected')) throw new Error('Internal labels exposed');
    if(pair.dataset.requirement!=='required') throw new Error('Required border');
    const optional=document.querySelector('.trainer-option[data-requirement="optional"]');
    if(!optional || getComputedStyle(optional).borderTopColor===getComputedStyle(pair).borderTopColor) throw new Error('Optional and required borders');
    if(getComputedStyle(pair.querySelector('.combatant-slot-heading')).textAlign!=='center') throw new Error('Slot label centering');
    pair.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
    if(document.querySelector('.trainer-continue').disabled) throw new Error('Keyboard selection');
    document.querySelector('.trainer-split-tabs button').click();
    if(!document.querySelector('.trainer-continue').disabled) throw new Error('Hidden split selection continued');
    tab.click();
    if(document.querySelector('.trainer-continue').disabled) throw new Error('Split selection restore');
    document.querySelector('[data-trainer-id="platinum-kaizo-veilstone-tag-battle"]').scrollIntoView({block:'start'});
  })()`, true);
  if (staged) await evaluate(page, `window.waitForSelectorTest(() => [...document.querySelectorAll('[data-trainer-id="platinum-kaizo-veilstone-tag-battle"] .trainer-portrait')].length===2 && [...document.querySelectorAll('[data-trainer-id="platinum-kaizo-veilstone-tag-battle"] .trainer-portrait')].every(image=>image.complete&&image.naturalWidth>0),'confirmed class sprites load')`,true);
  await evaluate(page, `window.waitForSelectorTest(() => document.querySelectorAll('.trainer-split-tabs img[data-asset-kind="badge-icon"]').length===10 && document.querySelectorAll('.trainer-split-tabs img[data-asset-kind="pokemon-sprite"]').length===1 && [...document.querySelectorAll('.trainer-split-tabs img')].every(image=>image.complete&&image.naturalWidth>0) && new URL(document.querySelector('.trainer-split-tabs img[data-asset-kind="pokemon-sprite"]').src).searchParams.get('form')==='question', 'PK badges and Other Battles question Unown load')`, true);
  for (const width of [1920,1280,390,320]) {
    await page.send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<600}); await delay(200);
    await evaluate(page, `(() => {document.querySelector('[data-trainer-id="platinum-kaizo-veilstone-tag-battle"]').scrollIntoView({block:'start'});document.querySelector('.trainer-split-tabs [aria-selected="true"]').scrollIntoView({block:'nearest',inline:'nearest'});})()`);
    const geometry = await evaluate(page, `(() => {const d=document.getElementById('trainer-selector-dialog'), list=d.querySelector('.trainer-options'), tabs=d.querySelector('.trainer-split-tabs'), f=d.querySelector('footer').getBoundingClientRect(), buttons=[...tabs.children];return {width:d.getBoundingClientRect().width,overflow:d.scrollWidth-d.clientWidth,listOverflow:list.scrollWidth-list.clientWidth,footerBottom:f.bottom,viewport:innerHeight,columns:getComputedStyle(list).gridTemplateColumns.split(' ').length,tabExcess:tabs.clientWidth-(buttons.reduce((sum,b)=>sum+b.getBoundingClientRect().width,0)+(buttons.length-1)*6+4)};})()`);
    assert.ok(geometry.width <= width && geometry.overflow <= 1 && geometry.listOverflow <= 1,JSON.stringify({width,...geometry}));
    assert.ok(geometry.footerBottom <= geometry.viewport,'Continue stays on screen');
    assert.equal(geometry.columns,1,'Trainer list stays in one column');
    if (width >= 1280) assert.ok(Math.abs(geometry.tabExcess) <= 2, 'Dialog fits the complete tab strip: '+JSON.stringify(geometry));
    const image=await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});
    await fs.writeFile(path.join(tempRoot,`trainer-selector-${width}.png`),Buffer.from(image.data,'base64'));
  }
  await evaluate(page, `(async () => {
    const wait=window.waitForSelectorTest;
    document.querySelector('.trainer-continue').click();
    await wait(()=>document.getElementById('plan-context-dialog').open,'continue into New Line');
    if(document.getElementById('trainer-select').value!=='platinum-kaizo-veilstone-tag-battle') throw new Error('Wrong encounter in New Line');
    if(document.getElementById('enemy-team-summary').querySelectorAll('.context-pokemon').length!==11) throw new Error('Lost multi roster');
    if(document.getElementById('player-partner-panel').hidden) throw new Error('Lost partner binding');
    document.getElementById('plan-context-dialog').close();
    document.getElementById('showdown-open').click();
    document.getElementById('showdown-text').value='Garchomp\\nLevel: 50\\nHardy Nature\\n- Earthquake';
    document.getElementById('import-showdown').click();
    await wait(()=>!document.getElementById('showdown-dialog').open,'fixture box');
    await window.openNewLineForTest();
    const change=(id,value)=>{const el=document.getElementById(id);el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));};
    change('trainer-select','platinum-kaizo-trainer-0309'); change('context-mode-select','sandbox');
    change('context-box-select',document.getElementById('context-box-select').options[1].value);
    await wait(()=>!document.getElementById('begin-plan').disabled,'fixture line readiness');
    document.getElementById('begin-plan').click();
    await wait(()=>!document.getElementById('plan-context-dialog').open,'begin fixture line');
    const title=document.getElementById('plan-toolbar-label').textContent;
    document.getElementById('new-plan').click();
    await wait(()=>document.getElementById('destructive-dialog').open,'save/discard before selector');
    if(document.getElementById('trainer-selector-dialog').open) throw new Error('Selector opened ahead of guard');
    document.getElementById('destructive-dialog').querySelector('[value="cancel"]').click();
    await wait(()=>!document.getElementById('destructive-dialog').open,'guard cancelled');
    await new Promise(r=>setTimeout(r,50));
    if(document.getElementById('trainer-selector-dialog').open) throw new Error('Guard cancellation ignored');
    document.getElementById('new-plan').click();
    await wait(()=>document.getElementById('destructive-dialog').open,'guard reopened');
    document.getElementById('destructive-discard').click();
    await wait(()=>document.getElementById('trainer-selector-dialog').open,'selector after discard');
    document.getElementById('trainer-selector-dialog').close('cancel');
    if(document.getElementById('plan-toolbar-label').textContent!==title) throw new Error('Cancelling cleared current line');
    await new Promise(r=>setTimeout(r,50));
    await window.openNewLineForTest();
    change('trainer-select','platinum-kaizo-trainer-0310');change('context-mode-select','sandbox');change('context-box-select',document.getElementById('context-box-select').options[1].value);
    document.getElementById('begin-plan').click();
    await wait(()=>!document.getElementById('plan-context-dialog').open,'begin without a second guard');
    if(document.getElementById('destructive-dialog').open) throw new Error('Duplicate destructive guard');
    document.getElementById('new-plan').click();
    await wait(()=>document.getElementById('destructive-dialog').open,'save draft guard');
    document.querySelector('#destructive-dialog [value="draft"]').click();
    await wait(()=>document.getElementById('trainer-selector-dialog').open,'selector after saved draft');
    if(!document.getElementById('app-status').textContent.includes('saved to Drafts')) throw new Error('Draft not saved before selector');
    document.getElementById('trainer-selector-dialog').close('cancel');
  })()`,true);
  assert.deepEqual(page.events.filter(event=>event.method==='Runtime.exceptionThrown'),[]);
  console.log(JSON.stringify({status:'trainer-selector-browser-valid',staged,multi:true,guardBeforeSelection:true,cancelPreservesPlan:true,widths:[1280,390,320]}));
}
