import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, "..");
const datasetFile = path.join(projectRoot, "src", "generated", "datasets", "volt-white-2r", "moves.json");
const outputFile = path.join(projectRoot, "src", "rulesets", "generated", "showdown_move_reference.js");
const expectedVersion = "0.11.11";
const packageIntegrity = "sha512-FdW7gt3TkG4AdXmpMTPYX2kx42VEfY8tQApjW9wEHOGzwH6Kn97wD0o5uIzAc4xpO1W+Tim70Ti9+FNkMNCA2w==";

function argument(name, fallback = null) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : fallback;
}

function isObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function mergeInherited(base, override) {
  if (!override) return base;
  const result = { ...base };
  for (const [key, value] of Object.entries(override)) {
    if (key === "inherit") continue;
    if (value === undefined) delete result[key];
    else if (isObject(value) && isObject(base?.[key])) result[key] = mergeInherited(base[key], value);
    else result[key] = value;
  }
  return result;
}

function callbackPaths(value, prefix = "", output = []) {
  if (typeof value === "function") {
    output.push(prefix);
    return output;
  }
  if (!value || typeof value !== "object") return output;
  for (const [key, child] of Object.entries(value)) {
    callbackPaths(child, prefix ? `${prefix}.${key}` : key, output);
  }
  return output;
}

function jsonSafe(value) {
  if (typeof value === "function" || value === undefined) return undefined;
  if (Array.isArray(value)) return value.map(jsonSafe).filter(entry => entry !== undefined);
  if (!isObject(value)) return value;
  const output = {};
  for (const [key, child] of Object.entries(value)) {
    const normalized = jsonSafe(child);
    if (normalized !== undefined) output[key] = normalized;
  }
  return output;
}

const retainedFields = Object.freeze([
  "status",
  "volatileStatus",
  "sideCondition",
  "slotCondition",
  "pseudoWeather",
  "weather",
  "terrain",
  "boosts",
  "self",
  "secondary",
  "secondaries",
  "drain",
  "recoil",
  "multihit",
  "multiaccuracy",
  "selfSwitch",
  "forceSwitch",
  "heal",
  "willCrit",
  "critRatio",
  "breaksProtect",
  "flags",
  "target",
  "condition"
]);

function extractMove(move) {
  const output = {};
  for (const field of retainedFields) {
    const value = jsonSafe(move[field]);
    if (value !== undefined && (!isObject(value) || Object.keys(value).length)) output[field] = value;
  }
  const callbacks = [...new Set(callbackPaths(move))].sort();
  if (callbacks.length) output.callbacks = callbacks;
  return output;
}

const packageRoot = path.resolve(argument(
  "--showdown-package-root",
  path.join(projectRoot, ".codex-tmp", "showdown-npm", "package")
));
const packageJson = JSON.parse(fs.readFileSync(path.join(packageRoot, "package.json"), "utf8"));
if (packageJson.name !== "pokemon-showdown" || packageJson.version !== expectedVersion) {
  throw new Error(`Expected pokemon-showdown ${expectedVersion}, found ${packageJson.name} ${packageJson.version}`);
}

const baseMoves = require(path.join(packageRoot, "dist", "data", "moves.js")).Moves;
const historicalMoveLayers = ["gen8", "gen7", "gen6", "gen5"].map(mod => ({
  mod,
  moves: require(path.join(packageRoot, "dist", "data", "mods", mod, "moves.js")).Moves
}));
const vw2rMoves = JSON.parse(fs.readFileSync(datasetFile, "utf8")).records;
const records = {};

for (const id of Object.keys(vw2rMoves).sort()) {
  const canonical = baseMoves[id];
  if (!canonical) throw new Error(`Showdown has no canonical move definition for ${id}`);
  const usesGen5Rules = Number(canonical.num) <= 559;
  const resolved = usesGen5Rules
    ? historicalMoveLayers.reduce((move, layer) => layer.moves[id] ? mergeInherited(move, layer.moves[id]) : move, canonical)
    : canonical;
  records[id] = {
    canonicalMoveNumber: Number(canonical.num),
    mechanicsGeneration: usesGen5Rules ? 5 : Number(canonical.gen || vw2rMoves[id].generation || 9),
    ...extractMove(resolved)
  };
}

const header = `// Generated by tools/build_showdown_move_reference.mjs. Do not edit by hand.\n`;
const body = `${header}export const SHOWDOWN_MOVE_REFERENCE = Object.freeze(${JSON.stringify(records, null, 2)});\n\nexport const SHOWDOWN_REFERENCE_SOURCE = Object.freeze(${JSON.stringify({
  package: `pokemon-showdown@${expectedVersion}`,
  integrity: packageIntegrity,
  moveCount: Object.keys(records).length,
  policy: "Showdown's Gen 8 through Gen 5 mod layers are applied in order for moves available in Black/White 2; later VW2R moves use their canonical definitions."
}, null, 2)});\n`;

if (process.argv.includes("--check")) {
  if (!fs.existsSync(outputFile) || fs.readFileSync(outputFile, "utf8") !== body) {
    throw new Error("Generated Showdown move reference is stale");
  }
  console.log(`Showdown move reference is current (${Object.keys(records).length} moves)`);
} else {
  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, body, "utf8");
  console.log(`Wrote ${path.relative(projectRoot, outputFile)} (${Object.keys(records).length} moves)`);
}
